export const product=[
    {
        id: 1,
        name: "White striped shirt",
        img: "https://i.pinimg.com/564x/e9/0c/e4/e90ce4c416caae483d02e807593a561e.jpg",
        type: "shirt",
        color: "white",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores illo maiores rerum dolorem dolor amet voluptatibus enim officia alias. Dolorem ducimus expedita ipsam sed error! Minima cumque quis pariatur facere?",
    },
    {
        id: 2,
        name: "Green shirt",
        img: "https://i.pinimg.com/736x/5d/c2/24/5dc22400123e5662bfb3b47ad20e956f.jpg",
        type: "shirt",
        color: "green",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores illo maiores rerum dolorem dolor amet voluptatibus enim officia alias. Dolorem ducimus expedita ipsam sed error! Minima cumque quis pariatur facere?",
    },
    {
        id: 3,
        name: "White shirt",
        img: "https://i.pinimg.com/564x/48/9d/c4/489dc428ef2b5b130b2b3f0d85f81f3a.jpg",
        type: "shirt",
        color: "white",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores illo maiores rerum dolorem dolor amet voluptatibus enim officia alias. Dolorem ducimus expedita ipsam sed error! Minima cumque quis pariatur facere?",
    },
    {
        id: 4,
        name: "Green hoodie",
        img: "https://i.pinimg.com/474x/36/2e/39/362e39ea579633e474715a0fecd117b4.jpg",
        type: "lounge",
        color: "green",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores illo maiores rerum dolorem dolor amet voluptatibus enim officia alias. Dolorem ducimus expedita ipsam sed error! Minima cumque quis pariatur facere?",
    },
    {
        id: 5,
        name: "Gray sweatshirt",
        img: "https://i.pinimg.com/474x/6a/8c/3a/6a8c3ad6bac05c32dc38f0b7dde79e8a.jpg",
        type: "lounge",
        color: "gray",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores illo maiores rerum dolorem dolor amet voluptatibus enim officia alias. Dolorem ducimus expedita ipsam sed error! Minima cumque quis pariatur facere?",
    },
    {
        id: 6,
        name: "Leather jacket",
        img: "https://i.pinimg.com/474x/85/88/60/858860f8cb551394b6bf6c3ff95fc83a.jpg",
        type: "jacket",
        color: "black",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores illo maiores rerum dolorem dolor amet voluptatibus enim officia alias. Dolorem ducimus expedita ipsam sed error! Minima cumque quis pariatur facere?",
    },
    {
        id: 7,
        name: "Blue and White jacket",
        img: "https://i.pinimg.com/474x/db/ea/7f/dbea7f28b90b58d018b9b68d3c633ba0.jpg",
        type: "jacket",
        color: "blue",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores illo maiores rerum dolorem dolor amet voluptatibus enim officia alias. Dolorem ducimus expedita ipsam sed error! Minima cumque quis pariatur facere?",
    },
    {
        id: 8,
        name: "Short white dress",
        img: "https://i.pinimg.com/474x/10/79/d5/1079d5bed4a12ebb7054a667039749d9.jpg",
        type: "dress",
        color: "white",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores illo maiores rerum dolorem dolor amet voluptatibus enim officia alias. Dolorem ducimus expedita ipsam sed error! Minima cumque quis pariatur facere?",
    },
    {
        id: 9,
        name: "Blue flower dress",
        img: "https://i.pinimg.com/474x/60/95/e7/6095e76ebbbfdde0b7b32854c775a7d9.jpg",
        type: "dress",
        color: "blue",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores illo maiores rerum dolorem dolor amet voluptatibus enim officia alias. Dolorem ducimus expedita ipsam sed error! Minima cumque quis pariatur facere?",
    },
    {
        id: 10,
        name: "Black jeans",
        img: "https://i.pinimg.com/474x/bb/62/65/bb62655a5afb933c6cb5f0431c25445d.jpg",
        type: "pant",
        color: "black",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores illo maiores rerum dolorem dolor amet voluptatibus enim officia alias. Dolorem ducimus expedita ipsam sed error! Minima cumque quis pariatur facere?",
    },
    {
        id: 11,
        name: "Blue jeans",
        img: "https://i.pinimg.com/474x/4a/db/16/4adb1693d87657287bcea3355dabd628.jpg",
        type: "pant",
        color: "jean",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores illo maiores rerum dolorem dolor amet voluptatibus enim officia alias. Dolorem ducimus expedita ipsam sed error! Minima cumque quis pariatur facere?",
    },
    // {
    //     id: 12,
    //     img: "https://i.pinimg.com/474x/8c/6f/f6/8c6ff655d0a9409a9432e696435053aa.jpg",
    //     type: "dress",
    // },
    // {
    //     id: 13,
    //     img: "https://i.pinimg.com/474x/9e/d8/f9/9ed8f9fdcfb80f49c8f92fdf0322ef8f.jpg",
    //     type: "dress",
    // },
    // {
    //     id: 14,
    //     img: "https://i.pinimg.com/474x/11/94/c6/1194c6e7180bf1e09fc60b80f1b65ca4.jpg",
    //     type: "jacket",
    // },
    // {
    //     id: 15,
    //     img: "https://i.pinimg.com/474x/4d/55/a2/4d55a275949eafbd00795aa5efe7db38.jpg",
    //     type: "shirt",
    // },
    // {
    //     id: 16,
    //     img: "https://i.pinimg.com/736x/75/81/91/758191ae8027a2029aedc33ea81e0cfd.jpg",
    //     type: "shirt",
    // },
    // {
    //     id: 17,
    //     img: "https://i.pinimg.com/474x/e3/80/be/e380be1221ef896a0c5d7cf34a6f75bf.jpg",
    //     type: "jacket",
    // },
    // {
    //     id: 18,
    //     img: "https://i.pinimg.com/474x/46/32/18/4632189dbff3a732d16f6a4693d42ad4.jpg",
    //     type: "dress",
    // },
    // {
    //     id: 19,
    //     img: "https://i.pinimg.com/474x/23/85/7c/23857c840366febbcfbf9b2ee396ed78.jpg",
    //     type: "dress",
    // },
    // {
    //     id: 19,
    //     img: "https://i.pinimg.com/474x/5e/63/64/5e6364b650f773629a7640788829c03e.jpg",
    //     type: "dress",
    // },
    // {
    //     id: 19,
    //     img: "https://i.pinimg.com/474x/76/ef/10/76ef10fc7a6bec130feb16ee93d87701.jpg",
    //     type: "dress",
    // },
]